site_name: GearBot
theme:
   name: spacelab
nav:
  - Home: 'index.md'
  - Commands: 'commands.md'
  - Guides:
      - Quickstart: 'Guides/quickstart.md'
      - Advanced permissions: 'Guides/permissions.md'
